# This file is managed by ServiceBot plugin - Semaphore. The content in this file is created using a common
# template and configurations in service.yml.
# Modifications in this file will be overwritten by generated content in the nightly run.
# For more information, please refer to the page:
# https://confluentinc.atlassian.net/wiki/spaces/Foundations/pages/2871296194/Add+SemaphoreCI
apiVersion: v1alpha
kind: Project
metadata:
  name: kafka-rest-images
  description: ""
spec:
  visibility: private
  repository:
    url: git@github.com:confluentinc/kafka-rest-images.git
    run_on:
    - branches
    - pull_requests
    pipeline_file: .semaphore/semaphore.yml
    integration_type: github_app
    status:
      pipeline_files:
      - path: .semaphore/semaphore.yml
        level: pipeline
    whitelist:
      branches:
      - master
      - main
      - /^\d+\.\d+\.x$/
      - /^\d+\.\d+\.\d+-cp\d+-rc\d+$/
      - /^\d+\.\d+\.\d+-rc\d+$/
      - /^gh-readonly-queue.*/
  custom_permissions: true
  debug_permissions:
  - empty
  - default_branch
  - non_default_branch
  - pull_request
  - forked_pull_request
  - tag
  attach_permissions:
  - default_branch
  - non_default_branch
  - pull_request
  - forked_pull_request
  - tag
  tasks:
  - name: cp-dockerfile-build
    scheduled: False
    branch: "master"
    pipeline_file: .semaphore/cp_dockerfile_build.yml
    parameters:
    - name: CONFLUENT_VERSION
      required: True
      default_value: "NONE"
      description: "Confluent Platform version."
    - name: PACKAGES_URL
      required: True
      default_value: "NONE"
      description: "S3 bucket url where the debian packages are located."
    - name: PACKAGES_MAVEN_URL
      required: True
      default_value: "NONE"
      description: "URL to Maven packages from upstream packaging job."
    - name: PACKAGING_BUILD_NUMBER
      required: True
      default_value: "NONE"
      description: "Build number of packaging job. Required except when doing promote to production. For promote to production only this will default to latest."
    - name: ALLOW_UNSIGNED
      required: True
      default_value: "False"
      description: "Allow unsigned packages."
      options:
       - True
       - False
    - name: CONFLUENT_DEB_VERSION
      required: True
      default_value: "1"
      description: "Debian package version."
  - name: cp-dockerfile-promote
    scheduled: False
    branch: "master"
    pipeline_file: .semaphore/cp_dockerfile_promote.yml
    parameters:
    - name: CONFLUENT_VERSION
      required: True
      default_value: "NONE"
      description: "Confluent Platform version."
    - name: IMAGE_REVISION
      required: True
      default_value: "1"
      description: "Revision for Docker images. This is used with promote to production only."
    - name: UPDATE_LATEST_TAG
      required: True
      default_value: "NONE"
      description: "Should the latest tag on docker hub be updated to point at this new image version."
    - name: PACKAGING_BUILD_NUMBER
      required: True
      default_value: "NONE"
      description: "Build number of packaging job. Required except when doing promote to production. For promote to production only this will default to latest."
    - name: PROMOTE_OS_TYPE
      required: True
      default_value: "ubi"
      description: "The image OS type to promote to DockerHub. Required only when doing promote to production."
      options:
       - deb
       - ubi
